In [ ]:
from __future__ import division
def izip(*iterables):
    # izip('ABCD', 'xy') --> Ax By
    iterables = map(iter, iterables)
    while iterables:
        yield tuple(map(next, list(iterables)))
import numpy as np
male=[1,2,3,4]
female=[1,2,3,4]
m_prefs=np.array([[1,2,3,4],[3,2,1,4],[1,2,4,3],[3,1,4,2]])
f_prefs=np.array([[1,2,3,4],[2,1,4,3],[2,3,1,4],[1,4,3,2]])
males=dict(izip(male,m_prefs))
females=dict(izip(female,f_prefs))
matches={}
for i in male:
    matches[i]=""
singles=male
while len(singles)!=0:
    for i in singles:
        np.delete(m_prefs,i-1,0)
        proposed=m_prefs[i-1,0]
        if proposed not in matches.values():
            matches[i]=proposed
            singles.remove(i)
        else:
            matches_inv={v:k for k, v in matches.items()}
            matched_male=matches_inv[proposed]
            
            f_prefs2=f_prefs[proposed].flatten()
            x=np.where(f_prefs2==i)
            y=np.where(f_prefs2==matched_male)
            if x<y:
                matches[i]=proposed
                singles.remove(i)
                matches[matched_male]=""
                singles.append(matched_male)
return matches
            

In [33]:
m_prefs=np.array([[1,2,3,4],[3,2,1,4],[1,2,4,3],[3,1,4,2]])
np.argwhere(m_prefs==3)
m_prefs2=m_prefs[1].flatten()
x=np.where(m_prefs2==2)
x

(array([1]),)

In [38]:
for i in range(20):
    print i
i

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


19

In [84]:
a=[1,2,3,4]
for i in a:
    print a[i]
a

2
3
4


IndexError: list index out of range

In [79]:
for i in m_prefs:
    print m_prefs[i-1,0]

    

[1 3 1 3]
[1 3 1 3]
[1 3 3 1]
[1 1 3 3]


In [65]:
m_prefs[0,0]

1

In [94]:

b=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])


[1 2 3]
[1 2 3]
[1 2 3]
